### ISSUE TITLE
Wither disappeared

### ISSUE THREAD

**Issue by therealph1x** [mb243/THBL#20]
I spawned a wither in a protected box near the Breeze region post. The res name is witherkiller. The wither spawned but on first explosion it disappeared. Is this normal when explode is set to False?

**Comment by mb243** [comment]
This looks to be intentional:

https://github.com/bekvon/Residence/blob/2759d7e81bad48d899af18487c06977cffa4ed14/src/com/bekvon/bukkit/residence/listeners/ResidenceEntityListener.java#L259-L266

If I'm reading this correctly, any entity which explodes and does not have permission to do this is removed.
