### ISSUE TITLE
Kicked for flying

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#65]
I was kicked for flying when not actually flying.

If you do /res tpset and then break the block below, next time to tp to there you will be standing in the air and kicked for flying.

**Comment by mb243** [comment]
http://epicpix.com/wp-content/uploads/2013/04/ff_51.jpg

**Comment by Acheron4171** [comment]
lmao

**Comment by RetroRadical** [comment]
Same issue. excessive kicking

**Comment by mb243** [comment]
Timestamps please?

**Comment by RetroRadical** [comment]
today.
3 times. 
7:11ish to 7:30

**Comment by mb243** [comment]
This is a weird one because the game is doing what it's supposed to be doing (teleporting you to your claim coordinates), and then doing what it's supposed to b doing again (kicking you for being in the air/flying too long). These are two things that are both working as intended to produce an unintended result. 

For this, I'm going to say to simply set your `res tpset` coordinates again to a spot on the ground to fix it yourself.
