### ISSUE TITLE
Anti Cheat

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#70]
My friend joined the server recently under the name gmankilla. While it is her brothers account, she install the launcher on her own device/computer and knows very little about the PC Minecraft scene. (Playing it only since Sunday) But, she has gotten warnings for flying, phasing, no knockback, and speeding up time. I can swear that I know she doesn't use cheats. What can be happening?

**Comment by mb243** [comment]
Your friend's violations were logged with pings ranging from 24ms to 1153ms. I'm not aware of any performance issues with the server, so this is most likely going to be due to client performance or network issues on their end which are causing latency between their client and the server. Not much I can do here. I suggest troubleshooting their PC and network connectivity.
