### ISSUE TITLE
The confiscating plugin

### ISSUE THREAD

**Issue by RetroRadical** [mb243/THBL#77]
This one is too much in my opinion.
We are a small server and this plugin is causing only trouble to the few devoted players here. I could see  this plugin being very useful if we had a larger player base. 

While I can agree that knockback on an axe may be "op". But, in no way will it ever out dps the similarly enchanted sword equivalent. Therefore, i dont believe it to be a game changing exploit and worth all this headache.

On behalf of Zad, he has lost multiple tools that he claims legit.

Same for me, I have lost several tools (and i think it took my shovel again, can not verify), and now, It has taken iron blocks from my chest I store the precious items in, the items I collected over the twenty days of play time here.

Please disable this plugin. I could see a more viable reason to install it if we had more players, but its only hurting the few players that want to be here longer and invest their time into creating on this server. This plugin is creating a "nanny-state" of the server and ruining the experience.

**Comment by mb243** [comment]
> Therefore, i dont believe it to be a game changing exploit and worth all this headache.

IMO, anything that exists that shouldn't is an exploit.

Part of the headache has been the way that this plugin enforces legal items combined with McMMO. Some McMMO abilities are applied to items as enchantments during the duration of their effect, which creates items which are are no longer legal items. While this can (and probably should) be changed now, it may revert at some point in the future. See here:

https://github.com/mcMMO-Dev/mcMMO/blob/8cbb57df977733cc6ee38755337679d9d50aaddc/src/main/resources/hidden.yml#L10

> On behalf of Zad, he has lost multiple tools that he claims legit.

If Zad has an issue, Zad should report the issue.

> i think it took my shovel again, can not verify

Only 7 items ever, nothing this week:

```
$ egrep -Ri "Confiscate.*Taking.*RetroRadical" 2017-07-2* | wc -l
0
$ egrep -Ri "Confiscate.*Taking.*RetroRadical" * | wc -l
7
```

> This plugin is creating a "nanny-state" of the server and ruining the experience.

The purpose of moderation plugins is to ensure that the game play experience remains consistent and to reduce the amount of ~~administrative effort~~ limited free time that's required to address in-game issues, exploits, and the like. Any quality plugin that helps moderate the in-game experience to prevent issues from happening in the first place should be considered, as long as its configuration doesn't cause an undue burden for players or do unexpected or game-breaking things that can't be resolved with adjusting configuration settings. In the case of this plugin, there were some configuration issues weren't fully anticipated, and adjustments have been made and some items were returned when the plugin was first rolled out.

As an aside this is almost always going to be the case when new plugins are introduced: The default configuration is going to be in line with the plugin authors expectations and will almost certainly not reflect the game style here, and settings will have to be adjusted, observed, and possibly adjusted again in order to get a good fit.

If you think that something is misconfigured or you think the current limits don't fit well, I'm happy to discuss it further if you can give specific suggestions or recommendations.

Also, please keep in mind that if this server doesn't fit your needs or your specific play style, you're welcome to play somewhere else or even set up your own server.
